### ISSUE TITLE
when I catkin_make，occur the following problem ,what can I do？

### ISSUE THREAD

**Issue by maomao0220** [leonardlohky/map_merge_3d#1]
![image](https://user-images.githubusercontent.com/64572122/148407732-7e63f3b4-cdaf-48b9-b46c-b55a675955ec.png)

**Comment by leonardlohky** [comment]
Hello, sorry for the late reply. You can remove these two lines from `matching.cpp` file:

#include <cpd/jsoncpp.hpp>
#include <cpd/nonrigid.hpp>

It is from another package that I was experimenting with briefly but stopped using, so you can remove it.
